project:
  type: website
  output-dir: _site

website:
  title: "FOR5187 | PREACT"
  #logo: "images/tiki.png"  # Make sure this path is correct
  navbar:
    left: []  # explicitly empty
    pinned: true

  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - href: quarto/index.qmd
        text: Home
      - href: quarto/quick_overview.ipynb
        text: Quick overview
      - href: quarto/documentation.ipynb
        text: Feature Database Documentation
      - section: Pipelines preprocessing
        contents:
        - href: quarto/EMA preprocessing.ipynb
          text: EMA preprocessing
        - href: quarto/Passive preprocessing.ipynb
          text: Passive preprocessing
        - href: quarto/ECG preprocessing.ipynb
          text: ECG preprocessing
      - href: quarto/about.qmd
        text: About

format:
  html:
    theme:
     - cosmo
     - brand
    css: quarto/styles.css
    toc: true
    # number-sections: true


